### PR TITLE
Update to include new MS Teams

### PR DESCRIPTION
**Pull request by allisonacs**
- Updated workflow to support new MS Teams (2024)
- Updated readme
- Updated semver to 1.1

### CODE REVIEW

**Review by jonashelgemo — CHANGES_REQUESTED** [review]
Very nice Allison, thank you for the PR! If you could rebase and squash the commits into a single commit, I'd gladly merge this 👍

**Comment by jonashelgemo** [comment]
If you're unsure how to do this, I could just do a squash-merge for you :)

**Comment by allisonacs** [comment]
@jonashelgemo if you don't mind doing the squash-merge for me, I'd appreciate it! That's outside my comfort zone.

**Comment by jonashelgemo** [comment]
@allisonacs done! Thanks for the contribution 👍

**Pull request merged**
